replicas: 1
registry: txt
policy: sync
priorityClassName: fairwinds-critical
resources:
  requests:
    cpu: 50m
    memory: 50Mi
  limits:
    cpu: 50m
    memory: 50Mi
domainFilters:
- dev.nfs.sh
rbac:
  create: 'true'
provider: aws
txtOwnerId: reckoner-demo
txtPrefix: reckoner-demo-
podAnnotations:
  ad.datadoghq.com/external-dns.check_names: |
    ["prometheus"]
  ad.datadoghq.com/external-dns.init_configs: |
    [{}]
  ad.datadoghq.com/external-dns.instances: |
    [
      {
        "prometheus_url": "http://%%host%%:7979/metrics",
        "namespace": "external-dns",
        "metrics": ["*_errors_total"],
        "max_returned_metrics": "1000"
      }
    ]